# Generated by Django 4.2.3 on 2023-08-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profileimage'),
        ('posting', '0003_remove_comment_feed_id_remove_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_comment', to='users.user'),
        ),
        migrations.AlterField(
            model_name='comment_image',
            name='image',
            field=models.ImageField(blank=True, default='media/posting/default_image.jpeg', null=True, upload_to='feed_images/'),
        ),
        migrations.AlterField(
            model_name='feed_image',
            name='image',
            field=models.ImageField(blank=True, default='media/posting/default_image.jpeg', null=True, upload_to='feed_images/'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.BigAutoField(help_text='Call ID', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('call_status', models.BooleanField(default=True)),
                ('call_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_call', to='users.user')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_in_call', to='posting.feed')),
            ],
            options={
                'db_table': 'Call',
            },
        ),
    ]
